### ISSUE TITLE
Cannot get projects

### ISSUE THREAD

**Issue by stephenprater** [jszwedko/circleci-cli#11]
the program fails to start with this error message:

`json: cannot unmarshal string into Go value of type bool`

I am using the 0.2.0-pre binaries.

I am presuming this is because the schema for the CircleCI API changed, but I don't know how to track it down at any lower level.

**Comment by jszwedko** [comment]
Hi @stephenprater,

Can you try rerunning with the `-d` flag? With `0.2.0-pre` it should output the struct field that it failed to deserialize.

**Comment by jszwedko** [comment]
Closing this out, but please feel free to re-open if you get a chance to run with debug.
