### ISSUE TITLE
cannot get projects

### ISSUE THREAD

**Issue by eyal-rounds** [jszwedko/circleci-cli#4]
```
eyal@eyal-Lenovo-Y50-70:~/develop/git/booyah-android$ circleci-cli projects
json: cannot unmarshal string into Go value of type bool
```

This is AFTER i've set `export CIRCLE_TOKEN=my_token` (before that i got 401 u need to loging first which is also bad error message since your cli does not have 'login' command, should be 'please supply API TOKEN either using -t or using CIRCLE_TOKEN environment variable.'

**Comment by jszwedko** [comment]
Unfortunately `circleci-projects` returns a user specific list of projects and Go's `encoding/json` doesn't give very helpful error messages when deserializing ([yet](https://go-review.googlesource.com/#/c/18692/). I see you also opened #5 which empower you to help, but in lieu of that, do you mind gist'ing the JSON returned from https://circleci.com/api/v1/projects?circle-token=XXXXX? If you feel more comfortable sharing directly with me rather than posting here, you can also send it via e-mail to me at jesse.szwedko@gmail.com.

And agreed, the current error behavior is basically to pass the exact error back from CircleCI, but we should handle at least 401s more gracefully -- I'll spin off a separate issue for that.

**Comment by eyal-rounds** [comment]
10x! :-)
i'll check the debug thingy u posted and see the json that gets back to me,
naturally i didn't expect u to go on nothing i want to understand what's
the problem, could very well be that u get htp 2xx response with error json
from circle API. and then your json parser fails. but i need to see it, i'm
not that experienced in GO (python\java\c) so i have a bit hard time
reading the code :-)

**Comment by jszwedko** [comment]
Hi @eyal-rounds,

Do you mind trying out the prerelease I created (https://github.com/jszwedko/circleci-cli/releases/tag/0.2.0-pre) and let me know what error message it gives you? I was able to vendor and make some adjustments to the JSON deserializing library to give more informative error messages. There is also a `-d` flag you can now use to enable debugging of the HTTP request and responses.

Thank you!

**Comment by eyal-rounds** [comment]
ok. 10x, will test and get back to u!

**Comment by eyal-rounds** [comment]
ok, tried it, the -d works great! i followed the Project ype and tried to figure out which boolean he can't parse, so one of two, either getting null for boolean is not acceptable by the json module OR one of the inner Project maps is having this issue, the only thing i can ask is if u have  a code that unmarshals only the top level componenets so i can test it on my own on ALL my objects.
i can write one myself but since i'm not a go developer it will probably take long time
(go program that takes as param a file name that contains a json string, reads it into a string and tries to parse it as a Project object)
i can then split the text i get from circle and run it one by one on ALL my "Project" objects and see if all are problematic or only one and if one of them then i can play with the fields to find out which is causing the issue.

**Comment by jszwedko** [comment]
@eyal-rounds awesome, I'm glad that worked for you. Can you post the exact error message that it is giving you? Just knowing the field name would might be enough to help me investigate and address.

**Comment by eyal-rounds** [comment]
yes i can,  once i'm next t  o my work pc tomorrow :-)
it basically says it can't unmarshal string value to Boolean from json object.

**Comment by jszwedko** [comment]
Closing this out, but please feel free to reopen if you are able to try out the latest release (which has the additional debug/error handling).

**Comment by eyal-rounds** [comment]
10x. will do.
