### ISSUE TITLE
no debug mode to see errors\logs

### ISSUE THREAD

**Issue by eyal-rounds** [jszwedko/circleci-cli#5]
Hi.
If i had `-d | --debug` that might:
1. print the full uri + headers of the request
2. print the full body of the request\ response in an orderly manner
3. print error in the line they occur like stacktrace

i could have discovered more easily where the error i get comes from and why...

**Comment by jszwedko** [comment]
Very much yes, when I went to go double check that this wasn't there, I found this local diff:

```go
diff --git a/main.go b/main.go
index b398638..84116e8 100644
--- a/main.go
+++ b/main.go
@@ -123,6 +123,11 @@ func main() {
                        Usage:  "API token to use to access CircleCI (not needed for displaying information about public repositories)",
                        EnvVar: "CIRCLE_TOKEN",
                },
+               cli.BoolFlag{
+                       Name:   "debug, d",
+                       Usage:  "Enable debug logging",
+                       EnvVar: "CIRCLE_DEBUG",
+               },
        }
        app.Before = func(c *cli.Context) (err error) {
                baseURL, err := url.Parse(c.String("host") + "/api/v1/")
```

so it is definitely a thought that I had, but regrettably I didn't get very far. I'll try to revisit this soon -- I don't think it would be too difficult to add.
